<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buildings</title>
    <style>
        /* Styles for building list */
        .building {
            margin-bottom: 20px;
            border: 1px solid #ccc;
            padding: 10px;
            border-radius: 5px;
        }

        .building-name {
            font-weight: bold;
            font-size: 18px;
            margin-bottom: 5px;
        }

        .building-address {
            font-style: italic;
            color: #666;
        }

        .add-button {
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .add-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h2>Buildings</h2>
    <div id="buildingList">
        <!-- Building list will be dynamically generated by PHP -->
        <?php
            // Connect to the database
            $host = "localhost";
            $port = "5432";
            $dbname = "evacuation";
            $user = "postgres";
            $db_password = "RootAdmin";
            
            $conn = pg_connect("host=$host port=$port dbname=$dbname user=$user password=$db_password");
            if (!$conn) {
                die("Connection failed");
            }

            // Fetch buildings from the database
            $query = "SELECT * FROM public.buildings";
            $result = pg_query($conn, $query);
            if ($result) {
                while ($row = pg_fetch_assoc($result)) {
                    echo '<div class="building">';
                    echo '<p class="building-name">' . $row['building_name'] . '</p>';
                    echo '<p class="building-address">' . $row['building_address'] . '</p>';
                    echo '<button class="add-button" data-building-id="' . $row['building_id'] . '">Add</button>';
                    echo '</div>';
                }
            } else {
                echo "Error fetching buildings";
            }

            // Close the connection
            pg_close($conn);
        ?>
    </div>

    <script>
        // Function to handle adding a building
        function addBuilding(buildingId) {
            console.log('Adding building with ID:', buildingId);
            // Send AJAX request to add_building.php with buildingId parameter
            fetch('add_building.php?building_id=' + buildingId)
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Building added successfully');
                    // Optionally, you can refresh the building list after adding
                     window.location.reload();
                } else {
                    alert('Error adding building: ' + data.message);
                }
            })
            .catch(error => {
                console.error('Error:', error);
                alert('Error adding building');
            });
        }

        // Add event listener to handle click on Add button
        document.addEventListener('DOMContentLoaded', function() {
            document.querySelectorAll('.add-button').forEach(button => {
                button.addEventListener('click', function() {
                    const buildingId = this.getAttribute('data-building-id');
                    addBuilding(buildingId);
                });
            });
        });
    </script>
</body>
</html>
